### ISSUE TITLE
Global button styles

### ISSUE THREAD

**Issue by danlamanna** [kitware-resonant/django-auth-style#37]
@jtomeck Am I right in reading this code?
https://github.com/girder/django-girder-style/blob/0429b624b12600a745a56c0ca1ab3c499de8f17a/tailwind/src/styles.scss#L56

It appears as though I can't have a `button` downstream that is unstyled? Can we remove this?

**Comment by jtomeck** [comment]
That's a good point, I didn't think about that when implementing it. Yeah, remove it.

**Comment by danlamanna** [comment]
But also inputs and forms and others? Won't this break all of the auth stuff? I think this is kind of what @brianhelba and I were wondering around the intended use of this.

**Comment by jtomeck** [comment]
This is a helper so you don't have to type 10-15 tailwind classes multiple times on every button sitewide. I think it's safe to remove `button` and keep `.button` and in the code just use `<button class="button">`.

Am I not understanding what you're asking?

**Comment by brianhelba** [comment]
Obsoleted by #85.
